### ISSUE TITLE
Refused to load the image 'http://localhost:5000/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'".

### ISSUE THREAD

**Issue by lx2720** [kolyad3v/big-mamas-mushroom-mania#2]
Hello! Thanks for your code, i just encountered some problem is that i use nodeV14 and type 'npm install' 'npm start' , this project could suceesfully run in 5000 , but when i visit it by web broswer ,the f12 error is 
`#0969DA`Refused to load the image 'http://localhost:5000/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by kolyad3v** [comment]
Hey I had no idea this comment was here. Tbh I need to re-write this entire fucking mess so I'll try sort this out while doing that.

**Comment by lx2720** [comment]
Okay, thank you
